### ISSUE TITLE
Download link is invisible

### ISSUE THREAD

**Issue by Siedlerchr** [JabRef/JabRefOnline#2158]
<img width="995" alt="grafik" src="https://github.com/JabRef/JabRefOnline/assets/320228/a50f6568-e7c1-4168-a957-a4e63ec1e309">

Related https://community.uploadcare.com/t/tailwind-css-reset-causes-the-background-for-the-main-button-to-be-white/2032

**Comment by dmbaturin** [comment]
The button seems visible for me now, but the text color choice for its non-hover version seems  atrocious regardless:
![image](https://github.com/JabRef/JabRefOnline/assets/482212/77926b5e-e01d-4de5-b9d0-3cc9db667519)

**Comment by k3KAW8Pnf7mkmdSMPHz27** [comment]
There will be a follow-up PR to https://github.com/JabRef/JabRefOnline/pull/2135.

I believe both the color and transparency issue is addressed in becem-gharbi/nuxt-naiveui version 1.2.4+

**Comment by dmbaturin** [comment]
Wait, it's merged but it's still not on the live version of jabref.org? I'm a bit confused.

**Comment by k3KAW8Pnf7mkmdSMPHz27** [comment]
@dmbaturin it is merged, but not deployed.

**Comment by Siedlerchr** [comment]
Deployment fails currently for some various reasons @tobiasdiez  any idea how to fix this?

**Comment by k3KAW8Pnf7mkmdSMPHz27** [comment]
@Siedlerchr I believe you have more context in https://github.com/Azure/static-web-apps-cli/issues/721

**Comment by k3KAW8Pnf7mkmdSMPHz27** [comment]
There is also this https://stackoverflow.com/questions/54309021/azure-nodejs-dist-directory-error-ebusy-or-files-silently-not-overriden

See
https://github.com/JabRef/JabRefOnline/blob/1a25e5ad22e28e4897fc40d29af08d4561045922/.github/workflows/deploy.yml#L61-L69

**Comment by Siedlerchr** [comment]
Why do we execute this on Windows? Does not make sense to me. From what I read and see this should also work on linux

**Comment by Siedlerchr** [comment]
Fixed the deployment but DL link is not working https://dev.www.jabref.org/

**Comment by Siedlerchr** [comment]
Fixed by https://github.com/JabRef/JabRefOnline/commit/3c0b75b5f9c7a1ba16351d6534c7883c83849fb6

**Comment by tobiasdiez** [comment]
Still needs a proper fix.

**Comment by Siedlerchr** [comment]
It was fixed by https://github.com/JabRef/JabRefOnline/commit/e5585024af82d80edfdfd93b07c7c0236e5ef1da 
<img width="1384" alt="grafik" src="https://github.com/JabRef/JabRefOnline/assets/320228/d2f8b353-9e4f-4150-b450-e9f1c3816d19">

but as the deployment was not working I first had to fix the github workflow.

**Comment by tobiasdiez** [comment]
Okay right, but this PR was not yet ready as its broke the storybook ui tests...
